### ISSUE TITLE
Labels on hover in Labels off mode

### ISSUE THREAD

**Issue by miklevin** [cosmograph-org/cosmograph-issues#10]
The issue: Labels Off makes beautiful images that are easy to spot patterns, zoom in and out and otherwise navigate. This process is used for investigation processes such as finding nodes that are extreme hubs. But then you have to either toggle labels on or click on the node itself to see the label of the node you're looking at. Each of these actions has a problem.

Toggling labels on interrupts flow. The movements of the pointer are excessive with constant toggling on and off of labels to do investigations creating excessive cognitive load and fatigue. 

Clicking on the node which shows the name of the node in the user interface to the left both interrupts flow by requiring the click in the first place and changes the rendering of the link graph based on a selected node. You then have to click off the node to get back the full visualization.

The solution I believe is to just use the Labels Off mode and to show the label on a mouse-over of a node. Either in tool tips style or in the user inreface are to the left. Either one will do.

For context, I use Cosmograph to diagnose issues with sites. Thanks for the great tool!

**Comment by rokotyan** [comment]
Thanks for the feedback @miklevin.

The latest version of Cosmograph has it implemented:
<img width="651" alt="image" src="https://github.com/cosmograph-org/cosmograph-issues/assets/755708/53e27501-ee6d-465a-b8b6-bfd223f10361">

**Comment by miklevin** [comment]
Thank you! This was noticed in live-use of the product and appreciated 👏
