### ISSUE TITLE
Ignore delimiter declaration line on CSV files

### ISSUE THREAD

**Issue by miklevin** [cosmograph-org/cosmograph-issues#13]
While it is not part of RFC 4180, it is still a common practice to use a line at the beginning of a CSV file to specify what the delimiter or separator is going to be. If you're using software that can export a huge link graph that inserts a line above the column definitions such as:

sep=,
Full URL,Destination Full URL

...it is a complete show stopper, because these files are too large to load in Excel or GSheets and nobody out there really knows enough about text editors, awk or programming to simply remove the first line of the file. 

![Screenshot 2024-02-15 at 7 58 35 AM](https://github.com/cosmograph-org/cosmograph-issues/assets/4175278/4f23b85b-e434-4428-be37-37825f2aa1c1)

So my request is for Cosmograph.app to recognize and skip such lines when present. Just skipping it is much more important than abiding by it. Assume it is commas just to get this working ASAP please, please, pretty please.

**Comment by rokotyan** [comment]
@miklevin We've updated the app with this feature, if you could test it with your data, that would be great.

**Comment by miklevin** [comment]
Tested, and such a wonderful reduction in friction in using the tool in context. Thank you! 🙏 👏👏👏
