### ISSUE TITLE
Background Color (or Alpha)

### ISSUE THREAD

**Issue by miklevin** [cosmograph-org/cosmograph-issues#14]
Hi my favorite network visualization folks. It's me again! This time, I'm looking to get rid of the awfully square feeling for such organically round shapes for when I drop them into presentation decks and stuff. Currently, Control+S uses the existing background color (Cosmograph.app) and doesn't give much leeway to change it or make diagrams look good against the presentation's default background colors (especially my favorite: white!). 

So the ask is for you to ether allow the background color to be settable in Cosmograph.app or for the exports to use alpha transparency on the saved png image and we as presentation designers simply must choose compatible colors to look good. I know there are color palate issues of "what works" and stuff. But currently, I have to load Gimp, use Color to Alpha, create a white background frame, copy/paste the foreground node graph a bunch of times to get it dark enough, then Export png. Very high friction.

Otherwise, have to use white rectangular (disruptive and imposing on the beauty of the presentation) blocks around the node diagrams. They look so lovely floating against a white background!

![link_graph_depth_3](https://github.com/cosmograph-org/cosmograph-issues/assets/4175278/0eeedb38-128e-45d7-acce-3213b1a996e6)

![link_graph_depth_3-white](https://github.com/cosmograph-org/cosmograph-issues/assets/4175278/b0764787-cd19-4637-a6b6-3cc3243bbaf0)

**Comment by Stukova** [comment]
@miklevin Thank you for bringing the issue to our attention, and I completely agree that saving PNG graphs with transparent backgrounds is more convenient for further work with the image. We have added support for setting a transparent background in Cosmos and updated [Cosmograph.app](https://cosmograph.app/run/), so you can now export screenshots by pressing the S button with a transparent background.

**Comment by miklevin** [comment]
As is my usual practice, I noticed you having made the change in actual use today 😂
And also as usual, thanks for your impressive responsiveness 👏

**Comment by rokotyan** [comment]
Thanks @miklevin!
