### ISSUE TITLE
Jupyter Notebook integration

### ISSUE THREAD

**Issue by miklevin** [cosmograph-org/cosmograph-issues#17]
I don't know how to even articulate this one. But isn't it time for Cosmograph to be embeddable in Jupyter Notebooks like matplotlib or bokeh. There's also the ipywidgets route which provides interactivity, which would seem right for Cosmograph, but is limited to JupyterLab and not Notebooks in general.

But I envision pip install cosmograph, then doing something like:

cosmo("graph.csv", "meta.csv")

...then up pops an interactive cosmograph!

**Comment by rokotyan** [comment]
Absolutely! We have it in our plans, but there's no timeline.

**Comment by vak** [comment]
i guess this issue is resolved now?

**Comment by rokotyan** [comment]
Yes, closing.

@miklevin In case you missed it, we've [announced](https://github.com/orgs/cosmograph-org/discussions/4.) Cosmograph for Python public beta a few days ago 🥳
