### ISSUE TITLE
Cosmograph app graph view should allow user-supplied layout coordinates

### ISSUE THREAD

**Issue by dhimmel** [cosmograph-org/cosmograph-issues#20]
Embedding mode at https://cosmograph.app/run/ requires the user to supply pre-calculated x and y columns to layout nodes but does not graph edges.

Graph mode does show edges but applies a layout simulation and has no option for the user to supply coordinates.

Here's an [example visualization](https://cosmograph.app/run/?data=https://gist.githubusercontent.com/dhimmel/c0333d85973285da981231f675dba3ec/raw/b97fc8e33db91d27fd466d665be09e0efbb523f4/cosmograph-mesh-edges.csv&meta=https://gist.githubusercontent.com/dhimmel/c0333d85973285da981231f675dba3ec/raw/b97fc8e33db91d27fd466d665be09e0efbb523f4/cosmograph-mesh-nodes.csv&gravity=0.24&repulsion=1&repulsionTheta=1.06&linkSpring=1&linkDistance=10&friction=0.85&renderLabels=true&renderHoveredLabel=true&renderLinks=true&linkArrows=true&nodeSizeScale=1&linkWidthScale=2&linkArrowsSizeScale=2&nodeSize=size-total%20links&nodeColor=color-mesh__ic__sanchez__scaled&nodeLabel=mesh_label&linkWidth=width-default&linkColor=color-default&) for which I would like to use the `x` and `y` node metadata fields for layout (see [this gist](https://gist.github.com/dhimmel/c0333d85973285da981231f675dba3ec)).

Bonus if the columns used for x and y position are configurable. This would allow me to explore multiple user-supplied layouts in one go.

**Comment by rokotyan** [comment]
@dhimmel In the current version opening network graphs without simulation is not supported. We'll see if we can add this quickly.

Thanks for sharing your network graph!

**Comment by rokotyan** [comment]
@dhimmel We've updated the app, feel free to give it another try (open as a graph and provide x/y metadata)

**Comment by dhimmel** [comment]
It works! [Example](https://cosmograph.app/run/?data=https://gist.githubusercontent.com/dhimmel/c0333d85973285da981231f675dba3ec/raw/382e4ffb09d073911399b0edc5a67a00f3fd33f6/cosmograph-mesh-edges.csv&meta=https://gist.githubusercontent.com/dhimmel/c0333d85973285da981231f675dba3ec/raw/382e4ffb09d073911399b0edc5a67a00f3fd33f6/cosmograph-mesh-nodes.csv&source=source&target=target&gravity=0.24&repulsion=1&repulsionTheta=1.06&linkSpring=1&linkDistance=10&friction=0.85&renderLabels=true&renderHoveredLabel=true&renderLinks=true&linkArrows=true&nodeSizeScale=1&linkWidthScale=2&linkArrowsSizeScale=2&nodeSize=size-total%20links&nodeColor=color-default&nodeLabel=mesh_label&linkWidth=width-default&linkColor=color-default&) that looks like:

![image](https://github.com/user-attachments/assets/fbaff647-a3b4-4f1d-b418-4335749067a9)



Thanks for the fast turnaround.
