### ISSUE TITLE
Won't load .csv files anymore

### ISSUE THREAD

**Issue by miklevin** [cosmograph-org/cosmograph-issues#7]
Any attempt to load an external CSV file results in showing Source column as "<!doctype" and Target columns as "html>". This is tested on Mac and Windows. Chrome Version 118.0.5993.117 (Official Build) (arm64) on Mac and Edge version 119.0.2151.58 on Windows. File load was attempted with drag and drop and file requestor.

**Comment by kolmakova** [comment]
Hi, @miklevin! It occured during today's update of the Cosmograph app. Thanks to this notice, we were able to correct this critical bug quickly. 

Fixed.

**Comment by miklevin** [comment]
Thanks, you're the best.
